name: halt
enable_halt: true
halt_max_steps: 16
eval_mode: think
batch_size: 256
eval_datasets:
  - ./datasets/gsm8k.json
  - ./datasets/gsm-hard.json
  - ./datasets/MultiArith.json
  - ./datasets/SVAMP.json
