name: halt_8_tool
enable_halt: true
halt_max_steps: 8
eval_mode: tool
batch_size: 256
eval_datasets:
  - ./datasets/gsm8k.json
  - ./datasets/gsm-hard.json
  - ./datasets/MultiArith.json
  - ./datasets/SVAMP.json
