name: no_halt_8
enable_halt: false
halt_max_steps: 8
eval_mode: think
batch_size: 256
eval_datasets:
  - ./datasets/gsm8k.json
  - ./datasets/gsm-hard.json
  - ./datasets/MultiArith.json
  - ./datasets/SVAMP.json
